#!/bin/bash

clear
for ((i=1;i<5;i++))
do
  if [ $i -eq 3 ];
  then
    echo "----------------------------------------------------------"
  else
    echo ""
  fi
done

gcc ./*.c ../common/*.c -lm -lpthread  -o c
gcc ./*.c ../common/*.c -lm -lpthread  -o c > output.log 2>&1

if [ ! -s "output.log" ]
then
  echo "---SUCCESS---"
  echo "run"
  ./c
else
  echo "xxxFAIlLxxx"
fi
